In [1]:
print("HI, git and py")

HI, git and py

In [1]:
3+4

7

In [2]:
# 210628 | Learn datasience as example
import pandas as pd

In [22]:
Rawdata = pd.read_spss("./Data/kyrbs2019.sav") 
# 파일 경로 위치가 계속해서 에러났음.
# 파일 위치는 현재 작업하고 있는 쥬피터 노트북의 폴더가 기준
# ./ 는 현재 쥬피터 노트북의 위치를 나타냄 거기서 시작하여, 경로를 설정해줘야함
# 원시자료를 다루고자 할 때, 변수들이 정리되어 있는 지침서나 코딩북을 참조할 것.

In [21]:
Target_DF = Rawdata[["SEX","AGE","HT","WT",
                     "E_S_RCRD","E_SES","PR_HT","PA_TOT",
                     "M_SLP_EN","AC_LT","TC_LT","INT_WD_MM","INT_WK_MM"]]
# 타겟 변수 추출(필요 변수 추출)

In [24]:
# 타켓 변수 한글이름 변환
Target_DF.columns=["성별","연령","키","몸무게"
                  "학업성적","경제상태","건강인지","운동일수","스트레스인지",
                  "피로회복정도","음주경험","흡연경험","주중_인터넷이용시간","주말_인터넷이용시간"]
#파이썬에는 한글 변수 사용이 가능하나 타 언어에서는 불가능함으로 사용 지양
#한글 변수보다는 영어 변수에 익숙해질 것

In [26]:
Target_DF

,성별,연령,키,몸무게학업성적,경제상태,건강인지,운동일수,스트레스인지,피로회복정도,음주경험,흡연경험,주중_인터넷이용시간,주말_인터넷이용시간
0,2.0,13.0,154.0,50.0,2.0,2.0,1.0,4.0,4.0,1.0,1.0,120.0,180.0
1,2.0,12.0,161.0,47.0,1.0,1.0,1.0,6.0,2.0,1.0,1.0,120.0,60.0
2,2.0,13.0,161.0,44.3,2.0,2.0,2.0,5.0,3.0,1.0,1.0,120.0,180.0
3,2.0,13.0,163.7,52.0,1.0,2.0,1.0,8.0,3.0,2.0,1.0,NaN,NaN
4,2.0,13.0,156.0,44.0,3.0,2.0,1.0,8.0,2.0,1.0,1.0,20.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57298,1.0,17.0,NaN,NaN,3.0,3.0,4.0,1.0,3.0,1.0,1.0,240.0,360.0
57299,2.0,18.0,NaN,NaN,4.0,2.0,3.0,1.0,5.0,1.0,1.0,60.0,60.0
57300,2.0,18.0,159.0,50.0,2.0,4.0,4.0,1.0,5.0,2.0,1.0,NaN,NaN
57301,2.0,18.0,153.7,63.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,130.0,80.0
57302,1.0,17.0,172.0,63.0,4.0,2.0,3.0,8.0,2.0,2.0,2.0,NaN,NaN

In [28]:
#NaN(Missing value, 결측값) 어떠한 연유로 값이 누락되었음
#결측값을 해결하는 문제는 데이터 분석에서 매우 민감하고 중요한 부분, 그러나 현재는 통계가 목적이 아니므로 간단히 해결하고감
Target_DF.isna().sum()

#결측값이 발생한 이유에 대한 분석은 보고서를 읽는 것이 가장 정확함

성별                0
연령              234
키              1555
몸무게학업성적        1555
경제상태              0
건강인지              0
운동일수              0
스트레스인지            0
피로회복정도            0
음주경험              0
흡연경험              0
주중_인터넷이용시간    14297
주말_인터넷이용시간    12488
dtype: int64

In [33]:
Target_DF["주중_인터넷이용시간"] = Target_DF.주중_인터넷이용시간.fillna(0)
Target_DF["주말_인터넷이용시간"] = Target_DF.주말_인터넷이용시간.fillna(0)
Target_DF.dropna(inplace = True)
Target_DF.reset_index(drop = True, inplace = True)
Target_DF
#settingWithCopyWarning
#Pandas의 메모리 절약하기 위한 방법인 데이터 종속성으로 인해 발생하는 문제
#기존의 RawData와 Target_DF가 별개로 존재하게 되므로 발생하는 문제
#이를 해결하기 위해 copy함수를 이용해서 Target_DF를 생성할 때, Rawdata와 별개로 흐르게 만들면 됨

<ipython-input-33-f7bbed51e144>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Target_DF["주중_인터넷이용시간"] = Target_DF.주중_인터넷이용시간.fillna(0)
<ipython-input-33-f7bbed51e144>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Target_DF["주말_인터넷이용시간"] = Target_DF.주말_인터넷이용시간.fillna(0)
<ipython-input-33-f7bbed51e144>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Target_DF.dropna(inplace = True)

,성별,연령,키,몸무게학업성적,경제상태,건강인지,운동일수,스트레스인지,피로회복정도,음주경험,흡연경험,주중_인터넷이용시간,주말_인터넷이용시간
0,2.0,13.0,154.0,50.0,2.0,2.0,1.0,4.0,4.0,1.0,1.0,120.0,180.0
1,2.0,12.0,161.0,47.0,1.0,1.0,1.0,6.0,2.0,1.0,1.0,120.0,60.0
2,2.0,13.0,161.0,44.3,2.0,2.0,2.0,5.0,3.0,1.0,1.0,120.0,180.0
3,2.0,13.0,163.7,52.0,1.0,2.0,1.0,8.0,3.0,2.0,1.0,0.0,0.0
4,2.0,13.0,156.0,44.0,3.0,2.0,1.0,8.0,2.0,1.0,1.0,20.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55743,1.0,18.0,170.1,73.0,4.0,5.0,2.0,4.0,3.0,1.0,1.0,0.0,0.0
55744,1.0,18.0,171.0,75.0,2.0,2.0,1.0,4.0,1.0,1.0,1.0,70.0,200.0
55745,2.0,18.0,159.0,50.0,2.0,4.0,4.0,1.0,5.0,2.0,1.0,0.0,0.0
55746,2.0,18.0,153.7,63.0,3.0,2.0,3.0,3.0,3.0,1.0,1.0,130.0,80.0
55747,1.0,17.0,172.0,63.0,4.0,2.0,3.0,8.0,2.0,2.0,2.0,0.0,0.0

In [34]:
#추출된 데이터 set을 저장해 놓기
Target_DF.to_csv("Data_for_study.csv", index = False)