[Step 1] 데이터 준비/ 기본 설정

In [1]:
# 기본 라이브러리 불러오기
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import pandas as pd
import numpy as np

# Breast Cancer 데이터셋 가져오기 (출처: UCI ML Repository)
uci_path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data'
df = pd.read_csv(uci_path, header=None)

In [2]:
df.head()

        0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [3]:
# 열 이름 지정
df.columns = ['id', 'clump', 'cell_size', 
              'cell_shape', 'adhesion', 'epithlial',
              'bare_nuclei', 'chromatin', 
              'normal_nucleoli', 'mitoses', 'class']

[Step 2] 데이터 탐색

In [4]:
# 데이터 자료형 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               699 non-null    int64
 1   clump            699 non-null    int64
 2   cell_size        699 non-null    int64
 3   cell_shape       699 non-null    int64
 4   adhesion         699 non-null    int64
 5   epithlial        699 non-null    int64
 6   bare_nuclei      699 non-null    object
 7   chromatin        699 non-null    int64
 8   normal_nucleoli  699 non-null    int64
 9   mitoses          699 non-null    int64
 10  class            699 non-null    int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB

In [5]:
# 데이터 살펴보기
df.head()

        id  clump  cell_size  ...  normal_nucleoli  mitoses  class
0  1000025      5          1  ...                1        1      2
1  1002945      5          4  ...                2        1      2
2  1015425      3          1  ...                1        1      2
3  1016277      6          8  ...                7        1      2
4  1017023      4          1  ...                1        1      2

[5 rows x 11 columns]

In [6]:
# 데이터 통계 요약정보 확인
df.describe()

                 id       clump  ...     mitoses       class
count  6.990000e+02  699.000000  ...  699.000000  699.000000
mean   1.071704e+06    4.417740  ...    1.589413    2.689557
std    6.170957e+05    2.815741  ...    1.715078    0.951273
min    6.163400e+04    1.000000  ...    1.000000    2.000000
25%    8.706885e+05    2.000000  ...    1.000000    2.000000
50%    1.171710e+06    4.000000  ...    1.000000    2.000000
75%    1.238298e+06    6.000000  ...    1.000000    4.000000
max    1.345435e+07   10.000000  ...   10.000000    4.000000

[8 rows x 10 columns]

In [7]:
# bare_nuclei 열의 자료형 변경 (문자열 ->숫자)
# bare_nuclei 열의 고유값 확인
df['bare_nuclei'].unique()

array(['1', '10', '2', '4', '3', '9', '7', '?', '5', '8', '6'],
      dtype=object)

In [8]:
df['bare_nuclei'].replace('?', np.nan, inplace=True)      # '?'을 np.nan으로 변경
df.dropna(subset=['bare_nuclei'], axis=0, inplace=True)   # 누락데이터 행을 삭제
df['bare_nuclei'] = df['bare_nuclei'].astype('int')       # 문자열을 정수형으로 변환

In [9]:
df['bare_nuclei'].unique()

array([ 1, 10,  2,  4,  3,  9,  7,  5,  8,  6])

In [10]:
df.describe()

                 id       clump  ...     mitoses       class
count  6.830000e+02  683.000000  ...  683.000000  683.000000
mean   1.076720e+06    4.442167  ...    1.603221    2.699854
std    6.206440e+05    2.820761  ...    1.732674    0.954592
min    6.337500e+04    1.000000  ...    1.000000    2.000000
25%    8.776170e+05    2.000000  ...    1.000000    2.000000
50%    1.171795e+06    4.000000  ...    1.000000    2.000000
75%    1.238705e+06    6.000000  ...    1.000000    4.000000
max    1.345435e+07   10.000000  ...   10.000000    4.000000

[8 rows x 11 columns]

In [11]:
# 속성(변수) 선택
X = df[['clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial',
        'bare_nuclei', 'chromatin', 'normal_nucleoli', 'mitoses']]  # 설명 변수 X
y = df['class']  # 예측 변수 Y

In [12]:
# 설명 변수 데이터를 정규화
X = preprocessing.StandardScaler().fit(X).transform(X)

In [13]:
# train data 와 test data로 구분(7:3 비율)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, 
                                                    random_state=10)
print('train data 개수: ', X_train.shape)
print('test data 개수: ', X_test.shape)

train data 개수:  (478, 9)
test data 개수:  (205, 9)

[Step 5] SVM 분류 모형 - sklearn 사용

In [14]:
# sklearn 라이브러리에서 SVM 분류 모형 가져오기
from sklearn import svm
# 모형 객체 생성 (기본값 kernel='rbf' 적용)
svm_model = svm.SVC()
# train data를 가지고 모형 학습
svm_model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
# test data를 가지고 y_hat을 예측 (분류) 
y_hat = svm_model.predict(X_test)

In [16]:
import pandas as pd
df = pd.DataFrame({'y_hat':y_hat,'y':y_test})
df['차이'] = df['y_hat'] == df['y']
df.head()

     y_hat  y    차이
286      4  4  True
272      4  4  True
455      4  4  True
457      4  4  True
247      4  4  True

In [17]:
print('오답 수:',len(df) - sum(df['차이']))

오답 수: 5

In [18]:
# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics 
svm_matrix = metrics.confusion_matrix(y_test, y_hat) 
svm_matrix

array([[127,   4],
       [  1,  73]])

In [19]:
# 모형 성능 평가 - 평가지표 계산
svm_report = metrics.classification_report(y_test, y_hat)  
print(svm_report)

              precision    recall  f1-score   support

           2       0.99      0.97      0.98       131
           4       0.95      0.99      0.97        74

    accuracy                           0.98       205
   macro avg       0.97      0.98      0.97       205
weighted avg       0.98      0.98      0.98       205